apiVersion: 1
datasources:
  - name: AquaVigil Synthetic InfluxDB
    uid: aquavigil-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: false
    jsonData:
      version: Flux
      organization: aquavigil-demo
      defaultBucket: sensors
    secureJsonData:
      token: ${AQUAVIGIL_INFLUX_TOKEN}
